name: Publish to NPM on Release PR Merge

on:
  pull_request:
    types: [closed]
    branches: [master, main]

jobs:
  publish:
    # Only run if PR was merged and head branch starts with 'release/'
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Setup npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Get version from package.json
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create and push git tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: |
            ## 🚀 What's New
            
            Release v${{ steps.version.outputs.version }}
            
            ## 📦 Installation
            
            ```bash
            # Using bun (recommended)
            bun add webfinger.js@${{ steps.version.outputs.version }}
            
            # Using npm
            npm install webfinger.js@${{ steps.version.outputs.version }}
            
            # Using yarn
            yarn add webfinger.js@${{ steps.version.outputs.version }}
            ```
            
            ## 🔗 Links
            
            - [NPM Package](https://www.npmjs.com/package/webfinger.js/v/${{ steps.version.outputs.version }})
            - [Documentation](https://github.com/silverbucket/webfinger.js#readme)
            - [Live Demo](https://silverbucket.github.io/webfinger.js/)
            
            ---
            🚀 Generated with automated release workflow
          draft: false
          prerelease: false

      - name: Publish to npm
        run: npm publish

      - name: Add publish summary
        run: |
          echo "## 📦 NPM Publish Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Git Tag**: v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub Release**: https://github.com/silverbucket/webfinger.js/releases/tag/v${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Package**: https://www.npmjs.com/package/webfinger.js/v/${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Demo**: https://silverbucket.github.io/webfinger.js/" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Release is now complete!"